services:
  db:
    image: mysql:8.0
    container_name: beatflow-db
    restart: always
    environment:
      MYSQL_DATABASE: beatflow
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: beatflowuser
      MYSQL_PASSWORD: beatflowpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: musicstream-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/beatflow
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"          # helpful to see queries in logs
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - ecommerce-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: musicstream-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

volumes:
  db_data:

networks:
  ecommerce-net:
    driver: bridge
